import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-tl from-sky-800 to-blue-950 bg-cover bg-center h-screen overflow-hidden"
      >

        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
