import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-center">
          <nav className="flex flex-grow justify-between items-center px-6 max-w-screen-xl h-24 text-white">
            <div className="flex items-center text-base">
              <Image src="/Logomark.png" alt="Logo" width={44} height={44} />
              <span className="ml-2 font-semibold text-xl">Layers</span>
            </div>
            <div className="inline-flex gap-8 border-[#232323] py-1 border rounded-[80px]">
              <button className="flex justify-center items-center py-4 w-40 shrink-0">home</button>
              <button className="flex justify-center items-center py-4 w-40 shrink-0">about</button>
              <button className="flex justify-center items-center py-4 w-40 shrink-0">project</button>
              <button className="flex justify-center items-center py-4 w-40 shrink-0">contact</button>
            </div>
            <div>
              <button className="">dribble</button>
              <button className="">facebook</button>
              <button className="">instagram</button>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>&copy; 2024 My Next.js App</p>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
